/** 双语 UI 文案。维度名 / 说明来自 config/scoring.json，不在这里重复维护。 */
import { describeDimensions } from "./scoring.mjs";

export type Lang = "zh" | "en";

export interface DimensionLabel {
  key: string;
  label: string;
  /** 小尺寸雷达图用的短名 */
  short: string;
  desc: string;
  weight: number;
}

export function dimensionLabels(lang: Lang): DimensionLabel[] {
  return describeDimensions(lang) as DimensionLabel[];
}

export const L = {
  zh: {
    siteName: "Agent Top10",
    tagline: "每日 AI Agent 项目解读",
    heroSub:
      "每天从 GitHub 上千个 AI Agent 相关项目中，按 star 增速选出最热的 10 个，并用 8 个可解释维度给出综合评分与解读。",
    todayTop: "AI Agent 项目 Top 10",
    archive: "历史归档",
    rankBy: "按近 7 天 star 增速排名",
    rankByWindow: (days: number) => `按近 ${days} 天 star 增量排名`,
    periodDaily: "日榜",
    periodWeekly: "周榜",
    periodMonthly: "月榜",
    periodLabel: "周期",
    coverageNote: (actual: number, requested: number) =>
      actual < requested
        ? `提示：当前历史数据仅覆盖 ${actual} 天（目标窗口 ${requested} 天），增量未做线性外推，请以实际覆盖天数为准。`
        : `窗口实际覆盖 ${actual} 天。`,
    partialMetricsNote:
      "提示：窗口内部分期数缺少完整指标快照（contributors / PR / issue / 许可证等），依赖这些字段的维度已从总分中剔除、其余维度权重重新归一，因此雷达图维度数少于 8 维。",
    baselineNote: (date: string) => `基线快照：${date}`,
    stars: "Stars",
    forks: "Forks",
    weekGain: "新增 star",
    dailyGain: "日均增星",
    growthRate: "增速",
    forksGain: "新增 fork",
    overall: "综合分",
    statWeekGain: "本周新增",
    intro: "它能做什么？",
    highlights: "核心亮点",
    dataPoints: "数据要点",
    tagLlm: "AI 解读",
    tagLlmNote: "由模型读仓库 README 写成，数字仍按当日数据生成",
    tagManual: "人工校对",
    tagManualNote: "这份解读经过人工编辑",
    tagRules: "规则生成",
    cardFromRepo: "仓库自述",
    cardFromRepoNote: "这行是仓库作者自己的描述原文（未翻译），未被截断的部分见详情页",
    tagRulesNote: "这段介绍由分类与话题标签模板拼装，没有读 README，只陈述已采集的客观信息",
    cons: "局限",
    fitFor: "谁适合用？",
    quickstart: "快速上手",
    viewDetail: "查看解读",
    repo: "GitHub 仓库",
    homepage: "官网",
    archiveEmpty: "暂无历史数据",
    backToList: "返回榜单",
    top1of: "No.1：",
    top1Gain: (n: string, days: number) => `近 ${days} 天 +${n} star`,
    entries: "个项目",
    totalGain: "窗口合计新增 star",
    createdNote: "首次收录",
    language: "主语言",
    rank: "排名",
    rankUp: "上升",
    rankDown: "下降",
    rankNew: "新上榜",
    rankSame: "持平",
    score: "得分",
    dimMeaning: "它衡量什么",
    scoreSummary: (
      overall: number,
      low: { label: string; value: number }[],
      high: { label: string; value: number }[]
    ) => {
      if (!low.length && !high.length) return "";
      const parts: string[] = [];
      if (low.length) parts.push(`主要被${low.map((f) => `${f.label} ${f.value}`).join("、")}拉低`);
      if (high.length) parts.push(`${high.map((f) => f.label).join("、")}是加分项`);
      return `综合分 ${overall}，${parts.join("；")}。`;
    },
    gainSource: "增速来源",
    momentTitle: "为什么现在上榜？",
    momentStreak: (n: number) => `连续第 ${n} 期上榜`,
    momentFirst: "本期首次上榜",
    momentUp: (n: number) => `排名较上期上升 ${n} 位`,
    momentRelease: (n: number) => `近 90 天有 ${n} 次发布，增速可能来自新版本`,
    momentFastBase: (rate: number) => `相对存量 star 的增速 ${rate}%，基数还小、涨得快`,
    momentStock: (stars: number, rate: number) =>
      `累计 ${Number(stars).toLocaleString("en-US")} star 的存量仓库，本期增量主要来自既有关注度（增速 ${rate}%）`,
    momentQuiet: "未识别到版本或排名事件，属自然增长",
    forkAnomalyNote: (pct: number) => `fork / star 比 ${pct}%，明显高于常见区间：多为课程作业、批量二次开发或刷量，不能当成热度信号`,
    sourceExactLabel: "精确差值",
    sourceEstimateLabel: "估算",
    sourceLowerBoundLabel: "保守下界",
    gainSourceNote: "精确差值＝两次快照直接相减；估算＝按事件流样本外推，可能有偏差",
    sourceLowerBoundNote: "事件流覆盖率不足，此处直接采用观测到的条数、不做外推，真实增量只会更高。",
    scoringMixedNote: (versions: string) =>
      `本周期聚合了多天数据，其中评分口径存在差异（${versions}），综合分之间的可比性有限。`,
    caliberCurrent: "最新口径",
    caliberLegacy: (v: string) => `历史口径 v${v}`,
    caliberUnknown: "历史口径",
    scoreCaliber: "评分口径",
    badgeNew: "NEW",
    badgeNewNote: "首次登上本榜",
    badgeRise: (n: number) => `上升 ${n} 位`,
    badgeRiseNote: (n: number) => `相比上一期排名上升 ${n} 位`,
    badgeStreak: (n: number) => `连榜 ${n} 期`,
    badgeStreakNote: (n: number) => `已连续 ${n} 期留在榜单上`,
    relatedTitle: "相关项目",
    relatedSimilar: "同类项目",
    relatedHot: "同期热门",
    relatedSimilarNote: "按分类与话题标签相似度推荐",
    relatedHotNote: "同一期榜单中增量最高的项目",
    caliberNote: (current: string) =>
      `评分口径版本 v${current}：分数由该版本引擎生成。历史期数据可能来自更早版本，跨期比较时请留意口径差异。`,
    growthRateNote: (days: number) => `增速＝近 ${days} 天新增 star ÷ 当前 star 总量`,
    sourceSnapshot: "快照差值",
    sourceStargazers: "stargazers 精确统计",
    sourceEvents: "事件流估算",
    sourceWindow: "窗口快照差值",
    trend: "star 趋势",
    trendEmpty: "历史快照不足，暂无法绘制趋势",
    trendPoints: "个快照点",
    pool: "候选池",
    candidates: "个候选项目",
    search: "搜索项目 / 标签 / 语言",
    searchPlaceholder: "输入项目名、owner 或 topic…",
    searchEmpty: "没有匹配的项目",
    searchScope: (n: number) => `在最近 ${n} 期榜单中检索`,
    categories: "子分类",
    allCategories: "全部",
    category: "分类",
    topics: "话题标签",
    compare: "多仓库对比",
    compareTitle: "选择 2-5 个项目对比 star 走势",
    compareHint: "勾选项目后生成对比曲线；也可直接分享带参数的链接。",
    compareSelected: (n: number) => `已选 ${n} 个（最多 5 个）`,
    compareClear: "清空选择",
    compareNeed: "至少选择 2 个项目",
    exportData: "数据导出",
    exportCsv: "导出 CSV",
    exportJson: "导出 JSON",
    rss: "RSS",
    darkMode: "切换主题",
    periodSwitcher: "时间周期",
    prevPeriod: "上一期",
    nextPeriod: "下一期",
    readMore: "继续阅读",
    relatedProjects: "同期其它项目",
    dimensions: "维度",
    weight: "权重",
    dataQuality: "数据说明",
    dataQualityBody:
      "star 增量优先取历史快照的真实差值；快照缺失时回落到 GitHub stargazers 接口；超大仓库在事件流覆盖率不足时会被跳过，以保证排名公平。某一维度缺少可信输入时会被剔除、其余维度权重重新归一，而不是按 0 计入。评分公式在 0.2.0 做过量纲修正，因此 2026-09-23 及之后期数的分数水平与更早期数不可直接比较。",
    footerNote:
      "数据来自 GitHub 公开 API · 排名依据窗口内 star 增量 · 综合分为多维可解释评分结果",
    archiveIssues: "期",
    archiveByPeriod: "按周期浏览",
    allHistory: "全部历史",
    searchPage: "项目检索",
    exportPage: "数据导出",
    comparePage: "对比工具",
    errorTitle: "页面不存在",
    errorBody: "没有找到对应的榜单或项目。",
    backHome: "回到首页",
  },
  en: {
    siteName: "Agent Top10",
    tagline: "Daily AI Agent Project Reviews",
    heroSub:
      "Every day we pick the 10 hottest AI Agent projects on GitHub by star growth and score each across 8 explainable dimensions.",
    todayTop: "Top 10 AI Agent Projects",
    archive: "Archive",
    rankBy: "Ranked by 7-day star growth",
    rankByWindow: (days: number) => `Ranked by star gain over ${days} days`,
    periodDaily: "Daily",
    periodWeekly: "Weekly",
    periodMonthly: "Monthly",
    periodLabel: "Period",
    coverageNote: (actual: number, requested: number) =>
      actual < requested
        ? `Heads-up: available history covers only ${actual} of the requested ${requested} days. Gains are not extrapolated — read them as the actual covered window.`
        : `Window covers ${actual} days.`,
    partialMetricsNote:
      "Heads-up: some issues in this window lack a complete metric snapshot (contributors / PRs / issues / license), so the dimensions that depend on them were dropped and the remaining weights renormalised — that is why the radar shows fewer than 8 dimensions.",
    baselineNote: (date: string) => `Baseline snapshot: ${date}`,
    stars: "Stars",
    forks: "Forks",
    weekGain: "Star gain",
    dailyGain: "Stars/day",
    growthRate: "Growth",
    forksGain: "Fork gain",
    overall: "Overall",
    statWeekGain: "Weekly gain",
    intro: "What it does",
    highlights: "Highlights",
    dataPoints: "By the numbers",
    tagLlm: "AI-written review",
    tagLlmNote: "Written by a model from the repository README; every figure still comes from that day's data",
    tagManual: "Hand-edited review",
    tagManualNote: "This review was edited by a human",
    tagRules: "Template",
    cardFromRepo: "Repo's own description",
    cardFromRepoNote: "This line is the repository author's own description, untranslated; the detail page shows it in full",
    tagRulesNote: "Assembled from the project's category and topic tags without reading the README — it states only what was collected",
    cons: "Limitations",
    fitFor: "Who is it for",
    quickstart: "Quick start",
    viewDetail: "Read review",
    repo: "GitHub repo",
    homepage: "Homepage",
    archiveEmpty: "No archived data yet",
    backToList: "Back to ranking",
    top1of: "No.1: ",
    top1Gain: (n: string, days: number) => `+${n} stars in ${days} days`,
    entries: "projects",
    totalGain: "Combined star gain",
    createdNote: "First featured",
    language: "Language",
    rank: "Rank",
    rankUp: "Up",
    rankDown: "Down",
    rankNew: "New",
    rankSame: "Same",
    score: "Score",
    dimMeaning: "What it measures",
    scoreSummary: (
      overall: number,
      low: { label: string; value: number }[],
      high: { label: string; value: number }[]
    ) => {
      if (!low.length && !high.length) return "";
      const parts: string[] = [];
      if (low.length) parts.push(`held back by ${low.map((f) => `${f.label} ${f.value}`).join(", ")}`);
      if (high.length) parts.push(`${high.map((f) => f.label).join(", ")} are strengths`);
      return `Overall ${overall}: ${parts.join("; ")}.`;
    },
    gainSource: "Growth source",
    momentTitle: "Why is it on the list now?",
    momentStreak: (n: number) => `On the board for ${n} issue(s) in a row`,
    momentFirst: "First appearance",
    momentUp: (n: number) => `Up ${n} rank(s) from the previous issue`,
    momentRelease: (n: number) => `${n} release(s) in the last 90 days — the gain may follow a new version`,
    momentFastBase: (rate: number) => `${rate}% of its own star base — small repo, fast climb`,
    momentStock: (stars: number, rate: number) =>
      `An established repo (${Number(stars).toLocaleString("en-US")} stars), so the gain mostly rides on existing attention (${rate}%)`,
    momentQuiet: "No release or rank event detected — organic growth",
    forkAnomalyNote: (pct: number) => `fork / star ratio of ${pct}% is far above the usual range — typically coursework, bulk forks or gaming, not a popularity signal`,
    sourceExactLabel: "Exact delta",
    sourceEstimateLabel: "Estimated",
    sourceLowerBoundLabel: "Lower bound",
    gainSourceNote: "Exact = two snapshots subtracted; estimated = extrapolated from an event-stream sample",
    sourceLowerBoundNote: "Event-stream coverage is too low, so the raw observed count is used without extrapolation — the real gain can only be higher.",
    scoringMixedNote: (versions: string) =>
      `This period aggregates multiple days whose scoring calibers differ (${versions}); overall scores are only loosely comparable.`,
    caliberCurrent: "Current caliber",
    caliberLegacy: (v: string) => `Legacy caliber v${v}`,
    caliberUnknown: "Legacy caliber",
    scoreCaliber: "Scoring caliber",
    badgeNew: "NEW",
    badgeNewNote: "First time on this board",
    badgeRise: (n: number) => `Up ${n}`,
    badgeRiseNote: (n: number) => `Climbed ${n} place(s) versus the previous period`,
    badgeStreak: (n: number) => `${n}-period streak`,
    badgeStreakNote: (n: number) => `Has stayed on the board for ${n} consecutive periods`,
    relatedTitle: "Related projects",
    relatedSimilar: "Similar projects",
    relatedHot: "Hot in the same period",
    relatedSimilarNote: "Recommended by category and topic similarity",
    relatedHotNote: "Highest star gain within the same period",
    caliberNote: (current: string) =>
      `Scoring caliber v${current}: scores are produced by this engine version. Historical periods may come from earlier versions — mind the caliber gap when comparing across periods.`,
    growthRateNote: (days: number) => `Growth = star gain over the last ${days} days ÷ current star total`,
    sourceSnapshot: "snapshot delta",
    sourceStargazers: "exact stargazers count",
    sourceEvents: "event-stream estimate",
    sourceWindow: "window snapshot delta",
    trend: "Star trend",
    trendEmpty: "Not enough snapshots to draw a trend yet",
    trendPoints: "snapshot points",
    pool: "Candidate pool",
    candidates: "candidate projects",
    search: "Search projects / tags / language",
    searchPlaceholder: "Project name, owner or topic…",
    searchEmpty: "No matching project",
    searchScope: (n: number) => `Searching the ${n} most recent issues`,
    categories: "Categories",
    allCategories: "All",
    category: "Category",
    topics: "Topics",
    compare: "Compare repos",
    compareTitle: "Pick 2-5 projects to compare star trajectories",
    compareHint: "Select projects to render a comparison chart; the URL carries the selection for sharing.",
    compareSelected: (n: number) => `${n} selected (max 5)`,
    compareClear: "Clear",
    compareNeed: "Select at least 2 projects",
    exportData: "Data export",
    exportCsv: "Export CSV",
    exportJson: "Export JSON",
    rss: "RSS",
    darkMode: "Toggle theme",
    periodSwitcher: "Period",
    prevPeriod: "Newer",
    nextPeriod: "Older",
    readMore: "Read more",
    relatedProjects: "Also featured",
    dimensions: "Dimensions",
    weight: "Weight",
    dataQuality: "About the data",
    dataQualityBody:
      "Star gains come from real snapshot deltas first, then the GitHub stargazers endpoint. Large repos with insufficient event-stream coverage are skipped rather than amplified, so the ranking stays fair. A dimension without trustworthy input is dropped and the remaining weights are renormalised rather than counted as zero. Scoring was renormalised in 0.2.0, so score levels for issues from 2026-09-23 onward are not directly comparable with earlier ones.",
    footerNote:
      "Data from the public GitHub API · Ranked by star gain over the window · Overall score is a multi-dimension, explainable evaluation",
    archiveIssues: "issue(s)",
    archiveByPeriod: "Browse by period",
    allHistory: "Full history",
    searchPage: "Project search",
    exportPage: "Data export",
    comparePage: "Compare tool",
    errorTitle: "Page not found",
    errorBody: "We couldn't find that ranking or project.",
    backHome: "Back to home",
  },
};

export type Strings = (typeof L)["zh"];

export function strings(lang: Lang): Strings {
  return L[lang] as Strings;
}
