/** 双语 UI 文案常量 */
export const L = {
  zh: {
    heroSub: "每天从 GitHub 上千个 AI Agent 相关项目中，按 star 增速选出最热的 10 个，并用 6 个维度（热度趋势 / 社区活跃 / 技术创新 / 实用完成度 / 生态潜力 / 健康可持续）给出综合评分与深度解读。",
    todayTop: "今日 AI Agent 项目 Top 10",
    archive: "历史榜单",
    rankBy: "按近 7 天 star 增速排名",
    stars: "Stars",
    forks: "Forks",
    weekGain: "7 天新增",
    dailyGain: "日均增星",
    growthRate: "增速",
    overall: "综合分",
    why: "为什么上榜",
    highlights: "亮点",
    cons: "局限",
    fitFor: "适合谁",
    quickstart: "快速上手",
    dims: [
      ["热度趋势", "Momentum"], ["社区活跃", "Community"], ["技术创新", "Innovation"],
      ["实用完成度", "Practicality"], ["生态潜力", "Ecosystem"], ["健康可持续", "Health"],
    ],
    viewDetail: "查看解读",
    repo: "GitHub 仓库",
    homepage: "官网",
    archiveEmpty: "暂无历史数据",
    backToList: "返回榜单",
    top1of: "No.1：",
    entries: "个项目",
    totalGain: "本周合计新增 star",
    createdNote: "首次收录",
  },
  en: {
    heroSub: "Every day we pick the 10 hottest AI Agent projects on GitHub ranked by star growth, and score each on six dimensions (momentum / community / innovation / practicality / ecosystem / health) with an in-depth review.",
    todayTop: "Today's Top 10 AI Agent Projects",
    archive: "Archive",
    rankBy: "Ranked by 7-day star growth",
    stars: "Stars",
    forks: "Forks",
    weekGain: "7-day gain",
    dailyGain: "Stars/day",
    growthRate: "Growth",
    overall: "Overall",
    why: "Why it made the list",
    highlights: "Highlights",
    cons: "Limitations",
    fitFor: "Best for",
    quickstart: "Quick start",
    dims: [
      ["热度趋势", "Momentum"], ["社区活跃", "Community"], ["技术创新", "Innovation"],
      ["实用完成度", "Practicality"], ["生态潜力", "Ecosystem"], ["健康可持续", "Health"],
    ],
    viewDetail: "Read review",
    repo: "GitHub repo",
    homepage: "Homepage",
    archiveEmpty: "No archived data yet",
    backToList: "Back to ranking",
    top1of: "No.1: ",
    entries: "projects",
    totalGain: "Combined 7-day stars",
    createdNote: "First featured",
  },
};
