/** 双语 UI 文案。维度名 / 说明来自 config/scoring.json，不在这里重复维护。 */
import { describeDimensions } from "./scoring.mjs";

export type Lang = "zh" | "en";

export interface DimensionLabel {
  key: string;
  label: string;
  /** 小尺寸雷达图用的短名 */
  short: string;
  desc: string;
  weight: number;
}

export function dimensionLabels(lang: Lang): DimensionLabel[] {
  return describeDimensions(lang) as DimensionLabel[];
}

export const L = {
  zh: {
    siteName: "Agent Top10",
    tagline: "每日 AI Agent 项目解读",
    heroSub:
      "每天从 GitHub 上千个 AI Agent 相关项目中，按 star 增速选出最热的 10 个，并用 8 个可解释维度给出综合评分与解读。",
    todayTop: "AI Agent 项目 Top 10",
    archive: "历史归档",
    rankBy: "按近 7 天 star 增速排名",
    rankByWindow: (days: number) => `按近 ${days} 天 star 增量排名`,
    periodDaily: "日榜",
    periodWeekly: "周榜",
    periodMonthly: "月榜",
    periodLabel: "周期",
    coverageNote: (actual: number, requested: number) =>
      actual < requested
        ? `提示：当前历史数据仅覆盖 ${actual} 天（目标窗口 ${requested} 天），增量未做线性外推，请以实际覆盖天数为准。`
        : `窗口实际覆盖 ${actual} 天。`,
    partialMetricsNote:
      "提示：窗口内部分期数缺少完整指标快照（contributors / PR / issue / 许可证等），依赖这些字段的维度已从总分中剔除、其余维度权重重新归一，因此雷达图维度数少于 8 维。",
    baselineNote: (date: string) => `基线快照：${date}`,
    stars: "Stars",
    forks: "Forks",
    weekGain: "新增 star",
    dailyGain: "日均增星",
    growthRate: "增速",
    forksGain: "新增 fork",
    overall: "综合分",
    why: "为什么上榜",
    highlights: "亮点",
    cons: "局限",
    fitFor: "适合谁",
    quickstart: "快速上手",
    viewDetail: "查看解读",
    repo: "GitHub 仓库",
    homepage: "官网",
    archiveEmpty: "暂无历史数据",
    backToList: "返回榜单",
    top1of: "No.1：",
    entries: "个项目",
    totalGain: "窗口合计新增 star",
    createdNote: "首次收录",
    language: "主语言",
    rank: "排名",
    rankUp: "上升",
    rankDown: "下降",
    rankNew: "新上榜",
    rankSame: "持平",
    scoreBreakdown: "评分维度（8 维，权重见配置）",
    scoreTooltipHint: "悬停查看维度说明",
    gainSource: "增速来源",
    sourceSnapshot: "快照差值",
    sourceStargazers: "stargazers 精确统计",
    sourceEvents: "事件流估算",
    sourceWindow: "窗口快照差值",
    estimated: "估算值",
    trend: "star 趋势",
    trendEmpty: "历史快照不足，暂无法绘制趋势",
    trendPoints: "个快照点",
    pool: "候选池",
    candidates: "个候选项目",
    search: "搜索项目 / 标签 / 语言",
    searchPlaceholder: "输入项目名、owner 或 topic…",
    searchEmpty: "没有匹配的项目",
    searchScope: (n: number) => `在最近 ${n} 期榜单中检索`,
    categories: "子分类",
    allCategories: "全部",
    category: "分类",
    topics: "话题标签",
    compare: "多仓库对比",
    compareTitle: "选择 2-5 个项目对比 star 走势",
    compareHint: "勾选项目后生成对比曲线；也可直接分享带参数的链接。",
    compareSelected: (n: number) => `已选 ${n} 个（最多 5 个）`,
    compareClear: "清空选择",
    compareNeed: "至少选择 2 个项目",
    exportData: "数据导出",
    exportCsv: "导出 CSV",
    exportJson: "导出 JSON",
    rss: "RSS",
    darkMode: "切换主题",
    periodSwitcher: "时间周期",
    prevPeriod: "上一期",
    nextPeriod: "下一期",
    readMore: "继续阅读",
    relatedProjects: "同期其它项目",
    dimensions: "维度",
    weight: "权重",
    dataQuality: "数据说明",
    dataQualityBody:
      "star 增量优先取历史快照的真实差值；快照缺失时回落到 GitHub stargazers 接口；超大仓库在事件流覆盖率不足时会被跳过，以保证排名公平。某一维度缺少可信输入时会被剔除、其余维度权重重新归一，而不是按 0 计入。评分公式在 0.2.0 做过量纲修正，因此 2026-09-23 及之后期数的分数水平与更早期数不可直接比较。",
    footerNote:
      "数据来自 GitHub 公开 API · 排名依据窗口内 star 增量 · 综合分为多维可解释评分结果",
    archiveIssues: "期",
    archiveByPeriod: "按周期浏览",
    allHistory: "全部历史",
    searchPage: "项目检索",
    exportPage: "数据导出",
    comparePage: "对比工具",
    errorTitle: "页面不存在",
    errorBody: "没有找到对应的榜单或项目。",
    backHome: "回到首页",
  },
  en: {
    siteName: "Agent Top10",
    tagline: "Daily AI Agent Project Reviews",
    heroSub:
      "Every day we pick the 10 hottest AI Agent projects on GitHub by star growth and score each across 8 explainable dimensions.",
    todayTop: "Top 10 AI Agent Projects",
    archive: "Archive",
    rankBy: "Ranked by 7-day star growth",
    rankByWindow: (days: number) => `Ranked by star gain over ${days} days`,
    periodDaily: "Daily",
    periodWeekly: "Weekly",
    periodMonthly: "Monthly",
    periodLabel: "Period",
    coverageNote: (actual: number, requested: number) =>
      actual < requested
        ? `Heads-up: available history covers only ${actual} of the requested ${requested} days. Gains are not extrapolated — read them as the actual covered window.`
        : `Window covers ${actual} days.`,
    partialMetricsNote:
      "Heads-up: some issues in this window lack a complete metric snapshot (contributors / PRs / issues / license), so the dimensions that depend on them were dropped and the remaining weights renormalised — that is why the radar shows fewer than 8 dimensions.",
    baselineNote: (date: string) => `Baseline snapshot: ${date}`,
    stars: "Stars",
    forks: "Forks",
    weekGain: "Star gain",
    dailyGain: "Stars/day",
    growthRate: "Growth",
    forksGain: "Fork gain",
    overall: "Overall",
    why: "Why it made the list",
    highlights: "Highlights",
    cons: "Limitations",
    fitFor: "Best for",
    quickstart: "Quick start",
    viewDetail: "Read review",
    repo: "GitHub repo",
    homepage: "Homepage",
    archiveEmpty: "No archived data yet",
    backToList: "Back to ranking",
    top1of: "No.1: ",
    entries: "projects",
    totalGain: "Combined star gain",
    createdNote: "First featured",
    language: "Language",
    rank: "Rank",
    rankUp: "Up",
    rankDown: "Down",
    rankNew: "New",
    rankSame: "Same",
    scoreBreakdown: "Score breakdown (8 dimensions)",
    scoreTooltipHint: "Hover a dimension for its definition",
    gainSource: "Growth source",
    sourceSnapshot: "snapshot delta",
    sourceStargazers: "exact stargazers count",
    sourceEvents: "event-stream estimate",
    sourceWindow: "window snapshot delta",
    estimated: "estimated",
    trend: "Star trend",
    trendEmpty: "Not enough snapshots to draw a trend yet",
    trendPoints: "snapshot points",
    pool: "Candidate pool",
    candidates: "candidate projects",
    search: "Search projects / tags / language",
    searchPlaceholder: "Project name, owner or topic…",
    searchEmpty: "No matching project",
    searchScope: (n: number) => `Searching the ${n} most recent issues`,
    categories: "Categories",
    allCategories: "All",
    category: "Category",
    topics: "Topics",
    compare: "Compare repos",
    compareTitle: "Pick 2-5 projects to compare star trajectories",
    compareHint: "Select projects to render a comparison chart; the URL carries the selection for sharing.",
    compareSelected: (n: number) => `${n} selected (max 5)`,
    compareClear: "Clear",
    compareNeed: "Select at least 2 projects",
    exportData: "Data export",
    exportCsv: "Export CSV",
    exportJson: "Export JSON",
    rss: "RSS",
    darkMode: "Toggle theme",
    periodSwitcher: "Period",
    prevPeriod: "Newer",
    nextPeriod: "Older",
    readMore: "Read more",
    relatedProjects: "Also featured",
    dimensions: "Dimensions",
    weight: "Weight",
    dataQuality: "About the data",
    dataQualityBody:
      "Star gains come from real snapshot deltas first, then the GitHub stargazers endpoint. Large repos with insufficient event-stream coverage are skipped rather than amplified, so the ranking stays fair. A dimension without trustworthy input is dropped and the remaining weights are renormalised rather than counted as zero. Scoring was renormalised in 0.2.0, so score levels for issues from 2026-09-23 onward are not directly comparable with earlier ones.",
    footerNote:
      "Data from the public GitHub API · Ranked by star gain over the window · Overall score is a multi-dimension, explainable evaluation",
    archiveIssues: "issue(s)",
    archiveByPeriod: "Browse by period",
    allHistory: "Full history",
    searchPage: "Project search",
    exportPage: "Data export",
    comparePage: "Compare tool",
    errorTitle: "Page not found",
    errorBody: "We couldn't find that ranking or project.",
    backHome: "Back to home",
  },
};

export type Strings = (typeof L)["zh"];

export function strings(lang: Lang): Strings {
  return L[lang] as Strings;
}
